using SaavedraCraft.Model.Interface;
using SaavedraCraft.Model.Interfaces;
using SaavedraCraft.Model.Resources;
using System;
using System.Collections.Generic;
using System.Text;

namespace QuarentineSurvival.Model.Actions
{
    public abstract class CombinableActionableResource<T> : SimpleResource, ICombinableResource, IActionable<T>
    {
        public CombinableActionableResource(int initialAmount, string name, float autoGeneratedIncrementPerTick = 0.1F) : base(initialAmount, name, autoGeneratedIncrementPerTick)
        {
        }

        public abstract bool CanCombineWith(IResource other);
        public abstract IResource CombineWith(IResource other);
        public abstract void NotifyRefreshActions(IHolder<T> receiber);
        public abstract void OnDestroyResource();
        public abstract List<IAction<T>> ShowAvailableActions();
    }

}
