using SaavedraCraft.Model.Interface;
using SaavedraCraft.Model.Resources;
using System;
using System.Collections.Generic;
using System.Text;

namespace QuarentineSurvival.Model.Actions
{
    public class TransformableActionableResource<T> : SimpleResource, IActionable<T>
    {
        public TransformableActionableResource(int initialAmount, string name, float autoGeneratedIncrementPerTick = 0.1F) : base(initialAmount, name, autoGeneratedIncrementPerTick)
        {
        }

        public void NotifyRefreshActions(IHolder<T> receiber)
        {
            throw new NotImplementedException();
        }

        public List<IAction<T>> ShowAvailableActions()
        {
            return new List<IAction<T>> { new TransformAction<T>() };
        }
    }

}
